### ISSUE TITLE
Discourse CSS conflict causing huge homepage entry

### ISSUE THREAD

**Issue by JBYoshi** [lukegb/discourse-spongepowered-navbar#2]
The navbar seems to be conflicting with [Discourse's desktop CSS](https://github.com/discourse/discourse/blob/master/app/assets/stylesheets/desktop/header.scss#L10), enlarging the home icon and therefore the entire Homepage entry in the menu.

![forums-spongepowered-org-homepage-link](https://cloud.githubusercontent.com/assets/12983479/15858452/33236072-2c86-11e6-927b-fdea3415f0e3.png)

I'm using Firefox 46.0.1 on Windows 8.1.

**Comment by lukegb** [comment]
Fixed in 06b3501f2beb3154c8b8270a91497b0e17c07c6f

**Comment by JBYoshi** [comment]
Thanks!
