### ISSUE TITLE
Update to correct visual branding

### ISSUE THREAD

**Issue by lukegb** [lukegb/discourse-spongepowered-navbar#3]
SpongePowered/SpongeHome#106

**Comment by lukegb** [comment]
@minecrell mind taking this one too? :P

**Comment by stephan-gh** [comment]
@lukegb I was looking at your code a few days ago, but to be honest I'm a bit confused about the mobile stuff you added in there - and I don't know how to test this either. :P

**Comment by lukegb** [comment]
It's not my fault - if the mobile stuff doesn't exist then it Causes Issues(TM), namely that when you have a small screen the logo is full-width. :(
