### ISSUE TITLE
Update to match homepage menu

### ISSUE THREAD

**Issue by JBYoshi** [lukegb/discourse-spongepowered-navbar#4]
**Sponge Forums** :white_check_mark: | [SpongeDocs](https://github.com/SpongePowered/sponge_docs_theme/issues/17) | [Ore](https://github.com/SpongePowered/Ore/issues/171) :white_check_mark: | [SpongeAuth](https://github.com/SpongePowered/SpongeAuth/issues/5) :white_check_mark:
* The homepage gives the forums an icon of `fa-comments` (plural), while the Discourse menu gives it an icon of `fa-comment` (singular).
* The homepage menu says "Docs", the Discourse menu says "SpongeDocs".
* The homepage menu says "Javadocs" (lowercase d), the Discourse menu says "JavaDocs" (capital D). The homepage menu (lowercase d) is [correct](http://www.oracle.com/technetwork/java/javase/documentation/index-jsp-135444.html).
* The homepage menu links to "Downloads" as https://www.spongepowered.org/downloads, the Discourse menu currently links to "Get Sponge" on a forums post.
* The homepage menu also has a "Chat" option (with an icon of `fa-comment`) linking to https://www.spongepowered.org/chat, which is not present on the Discourse menu.

**Comment by lukegb** [comment]
Patches welcome :)

I'm not going to have time to get to this until mid/late December.
